// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Partea2.Data;

namespace Partea2.Migrations
{
    [DbContext(typeof(Partea2Context))]
    [Migration("20220107185731_ProgramareServiciu")]
    partial class ProgramareServiciu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Partea2.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DoctorID")
                        .HasColumnType("int");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DoctorID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Partea2.Models.Doctor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramareID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProgramareID");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("Partea2.Models.Programare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumarulProgramarii")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientId");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("Partea2.Models.ProgramareServiciu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProgramareId")
                        .HasColumnType("int");

                    b.Property<int>("ServiciuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramareId");

                    b.HasIndex("ServiciuId");

                    b.ToTable("ProgramareServiciu");
                });

            modelBuilder.Entity("Partea2.Models.Serviciu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Serviciu");
                });

            modelBuilder.Entity("Partea2.Models.Client", b =>
                {
                    b.HasOne("Partea2.Models.Doctor", "Doctor")
                        .WithMany("Client")
                        .HasForeignKey("DoctorID");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Partea2.Models.Doctor", b =>
                {
                    b.HasOne("Partea2.Models.Programare", "Programare")
                        .WithMany()
                        .HasForeignKey("ProgramareID");

                    b.Navigation("Programare");
                });

            modelBuilder.Entity("Partea2.Models.Programare", b =>
                {
                    b.HasOne("Partea2.Models.Client", null)
                        .WithMany("Programare")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Partea2.Models.ProgramareServiciu", b =>
                {
                    b.HasOne("Partea2.Models.Programare", "Programare")
                        .WithMany("ProgramareServicii")
                        .HasForeignKey("ProgramareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Partea2.Models.Serviciu", "Serviciu")
                        .WithMany("ProgramareServicii")
                        .HasForeignKey("ServiciuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programare");

                    b.Navigation("Serviciu");
                });

            modelBuilder.Entity("Partea2.Models.Client", b =>
                {
                    b.Navigation("Programare");
                });

            modelBuilder.Entity("Partea2.Models.Doctor", b =>
                {
                    b.Navigation("Client");
                });

            modelBuilder.Entity("Partea2.Models.Programare", b =>
                {
                    b.Navigation("ProgramareServicii");
                });

            modelBuilder.Entity("Partea2.Models.Serviciu", b =>
                {
                    b.Navigation("ProgramareServicii");
                });
#pragma warning restore 612, 618
        }
    }
}
